### ISSUE TITLE
m_contentItem’ has incomplete type ‘QPointer<QQuickItem>

### ISSUE THREAD

**Issue by hellisabove** [cutefishos/fishui#4]
While trying to compile on ubuntu 20.04 I get this:

fishui/src/desktop/menupopupwindow.h:61:26: error: field ‘m_contentItem’ has incomplete type ‘QPointer<QQuickItem>’
   61 |     QPointer<QQuickItem> m_contentItem;
      |                          ^~~~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/qt5/QtGui/qvector3d.h:45,
                 from /usr/include/x86_64-linux-gnu/qt5/QtGui/qmatrix4x4.h:44,
                 from /usr/include/x86_64-linux-gnu/qt5/QtGui/QMatrix4x4:1,
                 from /usr/include/x86_64-linux-gnu/qt5/QtQuick/qsgnode.h:44,
                 from /usr/include/x86_64-linux-gnu/qt5/QtQuick/qsgrendererinterface.h:43,
                 from /usr/include/x86_64-linux-gnu/qt5/QtQuick/qquickwindow.h:44,
                 from /usr/include/x86_64-linux-gnu/qt5/QtQuick/QQuickWindow:1,
                 from /home/halphix/cutefish-build/fishui/src/desktop/menupopupwindow.h:23,
                 from /home/halphix/cutefish-build/fishui/build/src/FishUI_autogen/NTHHH2CSJL/moc_menupopupwindow.cpp:9,
                 from /home/halphix/cutefish-build/fishui/build/src/FishUI_autogen/mocs_compilation.cpp:2:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qmetatype.h:1377:1: note: declaration of ‘class QPointer<QQuickItem>’
 1377 | QT_FOR_EACH_AUTOMATIC_TEMPLATE_SMART_POINTER(QT_FORWARD_DECLARE_SHARED_POINTER_TYPES_ITER)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [src/CMakeFiles/FishUI.dir/build.make:115: src/CMakeFiles/FishUI.dir/FishUI_autogen/mocs_compilation.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:123: src/CMakeFiles/FishUI.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by reionwong** [comment]
Try to add `#include <QPointer>` to the header of `menupopupwindow.h`
